entries/forms.py
#!/usr/bin/env python3

import wtforms

from models import Entry

class EntryForm(wtforms.Form):
	title = wtforms.StringField('Title')
	body = wtforms.TextAreaField('Body')
	
	def save_entry(self, entry):
		self.populate_obj(entry)
		entry.generate_slug()
		return entry

entries/blueprint.py
#!/usr/bin/env python3

from app import db
from flask import Blueprint, redirect, render_template, request, url_for
from helpers import object_list
from models import Entry
from entries.forms import EntryForm

entries = Blueprint('entries', __name__, template_folder='templates')

@entries.route('/')
def index():
	entries = Entry.query.order_by(Entry.created_timestamp.desc())
	return entry_list('entries/index.html', entries)

@entries.route('/create/', methods=['GET', 'POST'])
def create():
	if request.method == 'POST':
		form = EntryForm(request.form)
		if form.validate():
			entry = form.save_entry(Entry())
			db.session.add(entry)
			db.session.commit()
			return redirect(url_for('entries.detail', slug=entry. slug))
	else:
			form = EntryForm() 
		
	return render_template('entries/create.html', form=form)

@entries.route('/<slug>/edit/', methods=['GET', 'POST'])
def edit(slug):
	entry = Entry.query.filter(Entry.slug == slug).first_or_404()
	if request.method == 'POST':
		form = EntryForm(request.form, obj=entry)
		if form.validate():
			entry = form.save_entry(entry) 
			db.session.add(entry)
			db.session.commit()
			return redirect(url_for('entries.detail', slug=entry.slug))
	else:
		form = EntryForm(obj=entry)
	return render_template('entries/edit.html', entry=entry, form=form)


@entries.route('/<slug>/delete/', methods=['GET', 'POST'])
def delete(slug):
	entry = Entry.query.filter(Entry.slug == slug).first_or_404()
	if request.method == 'POST':
		db.session.delete(entry)
		db.session.commit()
		return redirect(url_for('entries.index'))
		
	return render_template('entries/delete.html', entry=entry)


@entries.route('/<slug>/')
def detail(slug):
	entry = Entry.query.filter(Entry.slug == slug).first_or_404()
	return render_template('entries/detail.html', entry=entry)


def entry_list(template, query, **context):
	search = request.args.get('q')
	if search:
		query = query.filter( (Entry.body.contains(search)) | (Entry.title.contains(search)))
	
	return object_list(template, query, **context)

entries/templates/entries/base_entries.html
{% extends "base.html" %}
{% block sidebar %}
	<form class="form-inline well" method="get" role="form">
		<div class="input-group">
			<input class="form-control input-xs" name="q" placeholder="Search..." value="{{ request.args.get('q', '') }}" />
			<span class="input-group-btn">
				<button class="btn btn-default" type="submit">Go</button>
			</span>
		</div>
	</form>
{% endblock %}
{% block content %}
	{% include "includes/list.html" %}
{% endblock %}

entries/templates/entries/create.html
{% extends "base.html" %}
{% from "macros/form_field.html" import form_field %}

{% block title %}Create new entry{% endblock %}
{% block content_title %}Create new entry{% endblock %}
{% block content %}
	<form action="{{ url_for('entries.create') }}" class="form form-horizontal" method="post">
		{% for field in form %}
			{{ form_field(field) }}
		{% endfor %}
		<div class="form-group">
			<div class="col-sm-offset-3 col-sm-9">
				<button type="submit" class="btn btn-default">Create</button> 
				<a class="btn" href="{{ url_for('entries.index') }}">Cancel</a>
			</div>
		</div>
	</form>
{% endblock %}

entries/templates/entries/delete.html
{% extends "base.html" %}
{% block title %}{{ entry.title }}{% endblock %}
{% block content_title %}{{ entry.title }}{% endblock %}
{% block content %}
	<form action="{{ url_for('entries.delete', slug=entry.slug) }}" method="post">
		<fieldset>
			<legend>Delete this entry?</legend>
			<button class="btn btn-danger" type="submit">Delete</button>
			<a class="btn" href="{{ url_for('entries.detail', slug=entry. slug) }}">Cancel</a>
		</fieldset>
	</form>
{% endblock %}

entries/templates/entries/detail.html
{% extends "base.html" %}
{% block title %}
	{{ entry.title }}
{% endblock %}
{% block content_title %}
	{{ entry.title }}
{% endblock %}

{% block sidebar %}
	<p>Published {{ entry.created_timestamp.strftime('%m/%d/%Y') }}</p>
	<a href="{{ url_for('entries.edit', slug=entry.slug) }}">Edit</a> - 
	<a href="{{ url_for('entries.delete', slug=entry.slug) }}">Delete</a>
{% endblock %}

{% block content %}
	{{ entry.body }}
{% endblock %}

entries/templates/entries/edit.html
{% extends "base.html" %}
{% from "macros/form_field.html" import form_field %}

{% block title %}Edit {{ entry.title }}{% endblock %}
{% block content_title %}Edit {{ entry.title }}{% endblock %}
{% block content %}
	<form action="{{ url_for('entries.edit', slug=entry.slug) }}" class="form form-horizontal" method="post">
		{% for field in form %}
			{{ form_field(field) }}
		{% endfor %}
		<div class="form-group">
			<div class="col-sm-offset-3 col-sm-9">
				<button type="submit" class="btn btn-default">Save</button>
				<a class="btn" href="{{ url_for('entries.detail', slug=entry. slug) }}">Cancel</a>
			</div>
		</div>
	</form>
{% endblock %}

entries/templates/entries/index.html
{% extends "entries/base_entries.html" %}
{% block title %}Entries{% endblock %}
{% block content_title %}Entries{% endblock %}

{% block content %}
	{% include "includes/list.html" %}
{% endblock %}

entries/templates/includes/list.html
{% for entry in object_list.items %}
<p><a href="{{ url_for('entries.detail', slug=entry.slug) }}">{{ entry.title }}</a></p>
{% endfor %}